"""
Passport and Visa standard size presets and biometric specifications.
"""

PASSPORT_CONFIG = {
    "width_mm": 35.0,
    "height_mm": 45.0,
    "dpi": 300,
    "target_dpi": 300,
    "target_width_px": 413,       # 35mm @ 300 DPI
    "target_height_px": 531,      # 45mm @ 300 DPI
    "eye_line_ratio": 0.38,       # Balanced eyeline at 38%
    "eye_line_ratio_default": 0.38,
    "head_height_ratio": 0.58,    # 58% of canvas height (chin to top of hair)
    "head_height_ratio_min": 0.50,
    "head_height_ratio_max": 0.65,
    "head_height_ratio_default": 0.58,
    "top_margin_ratio": 0.12,     # 12% headroom margin above hair (clean margin)
    "bottom_margin_ratio": 0.30,  # 30% shoulder/neck transition
}

COUNTRY_PRESETS = {
    "india": {
        "name": "India",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "usa": {
        "name": "USA",
        "width_mm": 50.8,
        "height_mm": 50.8,
        "target_w_px": 600,
        "target_h_px": 600,
        "head_height_ratio": 0.56,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.69,
        "top_headroom_ratio": 0.14,
        "eye_line_ratio": 0.40,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "uk": {
        "name": "United Kingdom",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "light grey",
        "min_dpi": 300,
    },
    "canada": {
        "name": "Canada",
        "width_mm": 50,
        "height_mm": 70,
        "target_w_px": 591,
        "target_h_px": 827,
        "head_height_ratio": 0.46,
        "head_height_ratio_min": 0.44,
        "head_height_ratio_max": 0.52,
        "top_headroom_ratio": 0.15,
        "eye_line_ratio": 0.40,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "australia": {
        "name": "Australia",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "light grey",
        "min_dpi": 300,
    },
    "germany": {
        "name": "Germany",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "light grey",
        "min_dpi": 300,
    },
    "france": {
        "name": "France",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "light grey",
        "min_dpi": 300,
    },
    "europe": {
        "name": "European Union / Schengen",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "japan": {
        "name": "Japan",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "china": {
        "name": "China",
        "width_mm": 33,
        "height_mm": 48,
        "target_w_px": 390,
        "target_h_px": 567,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "uae": {
        "name": "UAE",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "saudi": {
        "name": "Saudi Arabia",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "brazil": {
        "name": "Brazil",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "russia": {
        "name": "Russia",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "south_africa": {
        "name": "South Africa",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    },
    "new_zealand": {
        "name": "New Zealand",
        "width_mm": 35,
        "height_mm": 45,
        "target_w_px": 413,
        "target_h_px": 531,
        "head_height_ratio": 0.58,
        "head_height_ratio_min": 0.50,
        "head_height_ratio_max": 0.65,
        "top_headroom_ratio": 0.12,
        "eye_line_ratio": 0.38,
        "bg_color": "white",
        "min_dpi": 300,
    }
}