// electron/src/jobs/jobModel.js

const JOB_TYPES = {
    PHOTO: "PHOTO",
    ID_CARD: "ID_CARD",
    CERTIFICATE: "CERTIFICATE",
    PVC_CARD: "PVC_CARD"
};

const JOB_SOURCES = {
    LOCAL: "LOCAL",
    ONLINE: "ONLINE"
};

const OVERALL_STATUS = {
    CREATED: "CREATED",
    PROCESSING: "PROCESSING",
    READY: "READY",
    PRINTING: "PRINTING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED"
};

const PROCESSING_STATUS = {
    WAITING: "WAITING",
    DOWNLOADING: "DOWNLOADING",
    PROCESSING: "PROCESSING",
    READY: "READY",
    FAILED: "FAILED"
};

const PRINT_STATUS = {
    NOT_PRINTED: "NOT_PRINTED",
    PRINTING: "PRINTING",
    PRINTED: "PRINTED",
    PRINT_FAILED: "PRINT_FAILED"
};

const SYNC_STATUS = {
    NOT_REQUIRED: "NOT_REQUIRED",
    PENDING: "PENDING",
    SYNCING: "SYNCING",
    SYNCED: "SYNCED",
    FAILED: "FAILED"
};

module.exports = {
    JOB_TYPES,
    JOB_SOURCES,
    OVERALL_STATUS,
    JOB_STATUS: OVERALL_STATUS,
    PROCESSING_STATUS,
    PRINT_STATUS,
    SYNC_STATUS
};
